### ISSUE TITLE
 User can see their car

### ISSUE THREAD

**Issue by Yi-Jacob** [jacobyi11/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  open a new HTML page
- [x] open a CSS layout page and a CSS style page and link them to the HTML doc
- [x] set the background of the page
- [x] find a top-down image of the car and get its image URL
- [x] put the image of the car over the green background
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
