### ISSUE TITLE
Issue-2 User can turn their car

### ISSUE THREAD

**Issue by Yi-Jacob** [jacobyi11/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create css styles for the directions of the car
- [x] open a JS page
- [x] add a query selector for the car 
- [x] add an event listener for the car 
- [x] update the cars direction based off the event listen in a JS function
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x]  Fix all errors.
