### ISSUE TITLE
Issue 3 User can start the car

### ISSUE THREAD

**Issue by Yi-Jacob** [jacobyi11/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add a data model to hold the car's location
- [x] update the data model based off the car's location with the direction
- [ ] apply CSS so the car "moves" on the screen (absolute position)
- [ ] change the cars box-offset styles 
- [ ] add an event listener and corresponding function
- [ ] move the car at a steady rate (16ms)
- [ ] test functionality and look for unnecessary code
- [ ] clean up code
